import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidenav from "@/components/Sidenav";
import Topnav from "@/components/Topnav";
import Providers from "@/lib/providers";
import { AuthProvider } from "@/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex bg-gray-50 text-gray-900`}
      >
        <AuthProvider>
          <section className="w-60 h-screen bg-gray-200">
            <Sidenav />
          </section>
          <section className="w-full">
            <Topnav />
            <main>
              <Providers>{children}</Providers>
            </main>
          </section>
        </AuthProvider>
      </body>
    </html>
  );
}
